Repository Check-Data-Out/velog-dashboard-v2-api, pull requests merged in 2025-05, with the labels that each got.

#28 [25.04.30 / TASK-177] Test - 사용자 / 게시물 Leaderboard 조회 API 통합 테스트 추가
  src/repositories/__test__/leaderboard.repo.integration.test.ts
  src/repositories/__test__/leaderboard.repo.test.ts
  src/repositories/leaderboard.repository.ts
  src/services/__test__/leaderboard.service.test.ts
  src/services/leaderboard.service.ts
Labels: enhancement

#30 [25.05.05 / TASK-182] Feature - middleware 인가 로직 전체 리펙토링, 그에 따른 대응 개발
  .github/workflows/test-ci.yaml
  src/controllers/post.controller.ts
  src/controllers/user.controller.ts
  src/exception/index.ts
  src/exception/token.exception.ts
  src/middlewares/__test__/auth.middleware.test.ts
  src/middlewares/auth.middleware.ts
  src/modules/__test__/velog.api.test.ts
  src/modules/token_encryption/aes_encryption.ts
  src/modules/velog/velog.api.ts
  src/modules/velog/velog.constans.ts
  src/modules/velog/velog.type.ts
  src/repositories/__test__/qr.repo.integration.test.ts
  src/repositories/__test__/qr.repo.test.ts
  src/repositories/user.repository.ts
  src/routes/leaderboard.router.ts
  src/routes/noti.router.ts
  src/routes/user.router.ts
  src/services/__test__/qr.service.test.ts
  src/services/user.service.ts
  src/types/dto/userWithToken.type.ts
  src/types/express.d.ts
  src/types/index.ts
  src/types/models/QRLoginToken.type.ts
  src/types/models/User.type.ts
  src/types/velog.type.ts
Labels: bug, enhancement

#31 [25.05.12 / TASK-179] Refactor - 타임존 이슈 모두 해결!!
  src/controllers/post.controller.ts
  src/modules/slack/slack.notifier.ts
  src/repositories/__test__/leaderboard.repo.integration.test.ts
  src/repositories/__test__/leaderboard.repo.test.ts
  src/repositories/__test__/post.repo.integration.test.ts
  src/repositories/__test__/post.repo.test.ts
  src/repositories/leaderboard.repository.ts
  src/repositories/post.repository.ts
  src/routes/post.router.ts
  src/services/__test__/post.service.test.ts
  src/services/post.service.ts
  src/types/dto/requests/getPostQuery.type.ts
  src/utils/__test__/date.util.test.ts
  src/utils/date.util.ts
Labels: bug, documentation, enhancement
