Repository Check-Data-Out/velog-dashboard-v2-api, pull requests merged in 2025-06, with the labels that each got.

#32 [25.06.02 / TASK-202] hotfix: 쿠키에 max-age 값 없어서 세션 쿠키로 인식되고, 브라우저 종료시 아에 쿠키 삭제되어버림
  src/controllers/user.controller.ts
Labels: bug

#35 [25.06.19 / TASK-208] Feature - cookie and usermodel update
  .github/workflows/test-ci.yaml
  src/controllers/__test__/user.controller.test.ts
  src/controllers/user.controller.ts
  src/repositories/user.repository.ts
  src/services/user.service.ts
  src/types/dto/userWithToken.type.ts
Labels: bug, documentation, enhancement

#37 [25.06.27 / TASK-210] Feature - 리더보드 username 대응 개발
  src/repositories/__test__/integration/leaderboard.repo.integration.test.ts
  src/repositories/__test__/leaderboard.repo.test.ts
  src/repositories/leaderboard.repository.ts
  src/services/__test__/leaderboard.service.test.ts
  src/services/leaderboard.service.ts
  src/types/dto/responses/leaderboardResponse.type.ts
Labels: enhancement
